name: release-dry-run
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - "release/stable"
      - "release/beta"
      - "release/next"

permissions:
  contents: read # for checkout

jobs:
  build:
    uses: ./.github/workflows/ci.yml
  release-dry-run:
    name: Release dry run
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: echo "hello world"
      - run: ls -la
      - run: poetry version
